const process = `abeezee: "ABeeZee",
abel: "Abel",
abhaya-libre: "Abhaya Libre",
abril-fatface: "Abril Fatface",
aclonica: "Aclonica",
acme: "Acme",
actor: "Actor",
adamina: "Adamina",
advent-pro: "Advent Pro",
aguafina-script: "Aguafina Script",
akronim: "Akronim",
aladin: "Aladin",
aldrich: "Aldrich",
alef: "Alef",
alegreya: "Alegreya",
alegreya-sc: "Alegreya SC",
alegreya-sans: "Alegreya Sans",
alegreya-sans-sc: "Alegreya Sans SC",
alex-brush: "Alex Brush",
alfa-slab-one: "Alfa Slab One",
alice: "Alice",
alike: "Alike",
alike-angular: "Alike Angular",
allan: "Allan",
allerta: "Allerta",
allerta-stencil: "Allerta Stencil",
allura: "Allura",
almendra: "Almendra",
almendra-display: "Almendra Display",
almendra-sc: "Almendra SC",
amarante: "Amarante",
amaranth: "Amaranth",
amatic-sc: "Amatic SC",
amatica-sc: "Amatica SC",
amethysta: "Amethysta",
amiko: "Amiko",
amiri: "Amiri",
amita: "Amita",
anaheim: "Anaheim",
andada: "Andada",
andika: "Andika",
angkor: "Angkor",
annie-use-your-telescope: "Annie Use Your Telescope",
anonymous-pro: "Anonymous Pro",
antic: "Antic",
antic-didone: "Antic Didone",
antic-slab: "Antic Slab",
anton: "Anton",
arapey: "Arapey",
arbutus: "Arbutus",
arbutus-slab: "Arbutus Slab",
architects-daughter: "Architects Daughter",
archivo-black: "Archivo Black",
archivo-narrow: "Archivo Narrow",
aref-ruqaa: "Aref Ruqaa",
arima-madurai: "Arima Madurai",
arimo: "Arimo",
arizonia: "Arizonia",
armata: "Armata",
arsenal: "Arsenal",
artifika: "Artifika",
arvo: "Arvo",
arya: "Arya",
asap: "Asap",
asar: "Asar",
asset: "Asset",
assistant: "Assistant",
astloch: "Astloch",
asul: "Asul",
athiti: "Athiti",
atma: "Atma",
atomic-age: "Atomic Age",
aubrey: "Aubrey",
audiowide: "Audiowide",
autour-one: "Autour One",
average: "Average",
average-sans: "Average Sans",
averia-gruesa-libre: "Averia Gruesa Libre",
averia-libre: "Averia Libre",
averia-sans-libre: "Averia Sans Libre",
averia-serif-libre: "Averia Serif Libre",
bad-script: "Bad Script",
bahiana: "Bahiana",
baloo: "Baloo",
baloo-bhai: "Baloo Bhai",
baloo-bhaina: "Baloo Bhaina",
baloo-chettan: "Baloo Chettan",
baloo-da: "Baloo Da",
baloo-paaji: "Baloo Paaji",
baloo-tamma: "Baloo Tamma",
baloo-thambi: "Baloo Thambi",
balthazar: "Balthazar",
bangers: "Bangers",
barrio: "Barrio",
basic: "Basic",
battambang: "Battambang",
baumans: "Baumans",
bayon: "Bayon",
belgrano: "Belgrano",
belleza: "Belleza",
benchnine: "BenchNine",
bentham: "Bentham",
berkshire-swash: "Berkshire Swash",
bevan: "Bevan",
bigelow-rules: "Bigelow Rules",
bigshot-one: "Bigshot One",
bilbo: "Bilbo",
bilbo-swash-caps: "Bilbo Swash Caps",
biorhyme: "BioRhyme",
biorhyme-expanded: "BioRhyme Expanded",
biryani: "Biryani",
bitter: "Bitter",
black-ops-one: "Black Ops One",
bokor: "Bokor",
bonbon: "Bonbon",
boogaloo: "Boogaloo",
bowlby-one: "Bowlby One",
bowlby-one-sc: "Bowlby One SC",
brawler: "Brawler",
bree-serif: "Bree Serif",
bubblegum-sans: "Bubblegum Sans",
bubbler-one: "Bubbler One",
buda: "Buda",
buenard: "Buenard",
bungee: "Bungee",
bungee-hairline: "Bungee Hairline",
bungee-inline: "Bungee Inline",
bungee-outline: "Bungee Outline",
bungee-shade: "Bungee Shade",
butcherman: "Butcherman",
butterfly-kids: "Butterfly Kids",
cabin: "Cabin",
cabin-condensed: "Cabin Condensed",
cabin-sketch: "Cabin Sketch",
caesar-dressing: "Caesar Dressing",
cagliostro: "Cagliostro",
cairo: "Cairo",
calligraffitti: "Calligraffitti",
cambay: "Cambay",
cambo: "Cambo",
candal: "Candal",
cantarell: "Cantarell",
cantata-one: "Cantata One",
cantora-one: "Cantora One",
capriola: "Capriola",
cardo: "Cardo",
carme: "Carme",
carrois-gothic: "Carrois Gothic",
carrois-gothic-sc: "Carrois Gothic SC",
carter-one: "Carter One",
catamaran: "Catamaran",
caudex: "Caudex",
caveat: "Caveat",
caveat-brush: "Caveat Brush",
cedarville-cursive: "Cedarville Cursive",
ceviche-one: "Ceviche One",
changa: "Changa",
changa-one: "Changa One",
chango: "Chango",
chathura: "Chathura",
chau-philomene-one: "Chau Philomene One",
chela-one: "Chela One",
chelsea-market: "Chelsea Market",
chenla: "Chenla",
cherry-cream-soda: "Cherry Cream Soda",
cherry-swash: "Cherry Swash",
chewy: "Chewy",
chicle: "Chicle",
chivo: "Chivo",
chonburi: "Chonburi",
cinzel: "Cinzel",
cinzel-decorative: "Cinzel Decorative",
clicker-script: "Clicker Script",
coda: "Coda",
coda-caption: "Coda Caption",
codystar: "Codystar",
coiny: "Coiny",
combo: "Combo",
comfortaa: "Comfortaa",
coming-soon: "Coming Soon",
concert-one: "Concert One",
condiment: "Condiment",
content: "Content",
contrail-one: "Contrail One",
convergence: "Convergence",
cookie: "Cookie",
copse: "Copse",
corben: "Corben",
cormorant: "Cormorant",
cormorant-garamond: "Cormorant Garamond",
cormorant-infant: "Cormorant Infant",
cormorant-sc: "Cormorant SC",
cormorant-unicase: "Cormorant Unicase",
cormorant-upright: "Cormorant Upright",
courgette: "Courgette",
cousine: "Cousine",
coustard: "Coustard",
covered-by-your-grace: "Covered By Your Grace",
crafty-girls: "Crafty Girls",
creepster: "Creepster",
crete-round: "Crete Round",
crimson-text: "Crimson Text",
croissant-one: "Croissant One",
crushed: "Crushed",
cuprum: "Cuprum",
cutive: "Cutive",
cutive-mono: "Cutive Mono",
damion: "Damion",
dancing-script: "Dancing Script",
dangrek: "Dangrek",
david-libre: "David Libre",
dawning-of-a-new-day: "Dawning of a New Day",
days-one: "Days One",
dekko: "Dekko",
delius: "Delius",
delius-swash-caps: "Delius Swash Caps",
delius-unicase: "Delius Unicase",
della-respira: "Della Respira",
denk-one: "Denk One",
devonshire: "Devonshire",
dhurjati: "Dhurjati",
didact-gothic: "Didact Gothic",
diplomata: "Diplomata",
diplomata-sc: "Diplomata SC",
domine: "Domine",
donegal-one: "Donegal One",
doppio-one: "Doppio One",
dorsa: "Dorsa",
dosis: "Dosis",
dr-sugiyama: "Dr Sugiyama",
droid-sans: "Droid Sans",
droid-sans-mono: "Droid Sans Mono",
droid-serif: "Droid Serif",
duru-sans: "Duru Sans",
dynalight: "Dynalight",
eb-garamond: "EB Garamond",
eagle-lake: "Eagle Lake",
eater: "Eater",
economica: "Economica",
eczar: "Eczar",
ek-mukta: "Ek Mukta",
el-messiri: "El Messiri",
electrolize: "Electrolize",
elsie: "Elsie",
elsie-swash-caps: "Elsie Swash Caps",
emblema-one: "Emblema One",
emilys-candy: "Emilys Candy",
engagement: "Engagement",
englebert: "Englebert",
enriqueta: "Enriqueta",
erica-one: "Erica One",
esteban: "Esteban",
euphoria-script: "Euphoria Script",
ewert: "Ewert",
exo: "Exo",
exo-2: "Exo 2",
expletus-sans: "Expletus Sans",
fanwood-text: "Fanwood Text",
farsan: "Farsan",
fascinate: "Fascinate",
fascinate-inline: "Fascinate Inline",
faster-one: "Faster One",
fasthand: "Fasthand",
fauna-one: "Fauna One",
federant: "Federant",
federo: "Federo",
felipa: "Felipa",
fenix: "Fenix",
finger-paint: "Finger Paint",
fira-mono: "Fira Mono",
fira-sans: "Fira Sans",
fira-sans-condensed: "Fira Sans Condensed",
fira-sans-extra-condensed: "Fira Sans Extra Condensed",
fjalla-one: "Fjalla One",
fjord-one: "Fjord One",
flamenco: "Flamenco",
flavors: "Flavors",
fondamento: "Fondamento",
fontdiner-swanky: "Fontdiner Swanky",
forum: "Forum",
francois-one: "Francois One",
frank-ruhl-libre: "Frank Ruhl Libre",
freckle-face: "Freckle Face",
fredericka-the-great: "Fredericka the Great",
fredoka-one: "Fredoka One",
freehand: "Freehand",
fresca: "Fresca",
frijole: "Frijole",
fruktur: "Fruktur",
fugaz-one: "Fugaz One",
gfs-didot: "GFS Didot",
gfs-neohellenic: "GFS Neohellenic",
gabriela: "Gabriela",
gafata: "Gafata",
galada: "Galada",
galdeano: "Galdeano",
galindo: "Galindo",
gentium-basic: "Gentium Basic",
gentium-book-basic: "Gentium Book Basic",
geo: "Geo",
geostar: "Geostar",
geostar-fill: "Geostar Fill",
germania-one: "Germania One",
gidugu: "Gidugu",
gilda-display: "Gilda Display",
give-you-glory: "Give You Glory",
glass-antiqua: "Glass Antiqua",
glegoo: "Glegoo",
gloria-hallelujah: "Gloria Hallelujah",
goblin-one: "Goblin One",
gochi-hand: "Gochi Hand",
gorditas: "Gorditas",
goudy-bookletter-1911: "Goudy Bookletter 1911",
graduate: "Graduate",
grand-hotel: "Grand Hotel",
gravitas-one: "Gravitas One",
great-vibes: "Great Vibes",
griffy: "Griffy",
gruppo: "Gruppo",
gudea: "Gudea",
gurajada: "Gurajada",
habibi: "Habibi",
halant: "Halant",
hammersmith-one: "Hammersmith One",
hanalei: "Hanalei",
hanalei-fill: "Hanalei Fill",
handlee: "Handlee",
hanuman: "Hanuman",
happy-monkey: "Happy Monkey",
harmattan: "Harmattan",
headland-one: "Headland One",
heebo: "Heebo",
henny-penny: "Henny Penny",
herr-von-muellerhoff: "Herr Von Muellerhoff",
hind: "Hind",
hind-guntur: "Hind Guntur",
hind-madurai: "Hind Madurai",
hind-siliguri: "Hind Siliguri",
hind-vadodara: "Hind Vadodara",
holtwood-one-sc: "Holtwood One SC",
homemade-apple: "Homemade Apple",
homenaje: "Homenaje",
im-fell-dw-pica: "IM Fell DW Pica",
im-fell-dw-pica-sc: "IM Fell DW Pica SC",
im-fell-double-pica: "IM Fell Double Pica",
im-fell-double-pica-sc: "IM Fell Double Pica SC",
im-fell-english: "IM Fell English",
im-fell-english-sc: "IM Fell English SC",
im-fell-french-canon: "IM Fell French Canon",
im-fell-french-canon-sc: "IM Fell French Canon SC",
im-fell-great-primer: "IM Fell Great Primer",
im-fell-great-primer-sc: "IM Fell Great Primer SC",
iceberg: "Iceberg",
iceland: "Iceland",
imprima: "Imprima",
inconsolata: "Inconsolata",
inder: "Inder",
indie-flower: "Indie Flower",
inika: "Inika",
inknut-antiqua: "Inknut Antiqua",
irish-grover: "Irish Grover",
istok-web: "Istok Web",
italiana: "Italiana",
italianno: "Italianno",
itim: "Itim",
jacques-francois: "Jacques Francois",
jacques-francois-shadow: "Jacques Francois Shadow",
jaldi: "Jaldi",
jim-nightshade: "Jim Nightshade",
jockey-one: "Jockey One",
jolly-lodger: "Jolly Lodger",
jomhuria: "Jomhuria",
josefin-sans: "Josefin Sans",
josefin-slab: "Josefin Slab",
joti-one: "Joti One",
judson: "Judson",
julee: "Julee",
julius-sans-one: "Julius Sans One",
junge: "Junge",
jura: "Jura",
just-another-hand: "Just Another Hand",
just-me-again-down-here: "Just Me Again Down Here",
kadwa: "Kadwa",
kalam: "Kalam",
kameron: "Kameron",
kanit: "Kanit",
kantumruy: "Kantumruy",
karla: "Karla",
karma: "Karma",
katibeh: "Katibeh",
kaushan-script: "Kaushan Script",
kavivanar: "Kavivanar",
kavoon: "Kavoon",
kdam-thmor: "Kdam Thmor",
keania-one: "Keania One",
kelly-slab: "Kelly Slab",
kenia: "Kenia",
khand: "Khand",
khmer: "Khmer",
khula: "Khula",
kite-one: "Kite One",
knewave: "Knewave",
kotta-one: "Kotta One",
koulen: "Koulen",
kranky: "Kranky",
kreon: "Kreon",
kristi: "Kristi",
krona-one: "Krona One",
kumar-one: "Kumar One",
kumar-one-outline: "Kumar One Outline",
kurale: "Kurale",
la-belle-aurore: "La Belle Aurore",
laila: "Laila",
lakki-reddy: "Lakki Reddy",
lalezar: "Lalezar",
lancelot: "Lancelot",
lateef: "Lateef",
lato: "Lato",
league-script: "League Script",
leckerli-one: "Leckerli One",
ledger: "Ledger",
lekton: "Lekton",
lemon: "Lemon",
lemonada: "Lemonada",
libre-baskerville: "Libre Baskerville",
libre-franklin: "Libre Franklin",
life-savers: "Life Savers",
lilita-one: "Lilita One",
lily-script-one: "Lily Script One",
limelight: "Limelight",
linden-hill: "Linden Hill",
lobster: "Lobster",
lobster-two: "Lobster Two",
londrina-outline: "Londrina Outline",
londrina-shadow: "Londrina Shadow",
londrina-sketch: "Londrina Sketch",
londrina-solid: "Londrina Solid",
lora: "Lora",
love-ya-like-a-sister: "Love Ya Like A Sister",
loved-by-the-king: "Loved by the King",
lovers-quarrel: "Lovers Quarrel",
luckiest-guy: "Luckiest Guy",
lusitana: "Lusitana",
lustria: "Lustria",
macondo: "Macondo",
macondo-swash-caps: "Macondo Swash Caps",
mada: "Mada",
magra: "Magra",
maiden-orange: "Maiden Orange",
maitree: "Maitree",
mako: "Mako",
mallanna: "Mallanna",
mandali: "Mandali",
marcellus: "Marcellus",
marcellus-sc: "Marcellus SC",
marck-script: "Marck Script",
margarine: "Margarine",
marko-one: "Marko One",
marmelad: "Marmelad",
martel: "Martel",
martel-sans: "Martel Sans",
marvel: "Marvel",
mate: "Mate",
mate-sc: "Mate SC",
maven-pro: "Maven Pro",
mclaren: "McLaren",
meddon: "Meddon",
medievalsharp: "MedievalSharp",
medula-one: "Medula One",
meera-inimai: "Meera Inimai",
megrim: "Megrim",
meie-script: "Meie Script",
merienda: "Merienda",
merienda-one: "Merienda One",
merriweather: "Merriweather",
merriweather-sans: "Merriweather Sans",
metal: "Metal",
metal-mania: "Metal Mania",
metamorphous: "Metamorphous",
metrophobic: "Metrophobic",
michroma: "Michroma",
milonga: "Milonga",
miltonian: "Miltonian",
miltonian-tattoo: "Miltonian Tattoo",
miniver: "Miniver",
miriam-libre: "Miriam Libre",
mirza: "Mirza",
miss-fajardose: "Miss Fajardose",
mitr: "Mitr",
modak: "Modak",
modern-antiqua: "Modern Antiqua",
mogra: "Mogra",
molengo: "Molengo",
molle: "Molle",
monda: "Monda",
monofett: "Monofett",
monoton: "Monoton",
monsieur-la-doulaise: "Monsieur La Doulaise",
montaga: "Montaga",
montez: "Montez",
montserrat: "Montserrat",
montserrat-alternates: "Montserrat Alternates",
montserrat-subrayada: "Montserrat Subrayada",
moul: "Moul",
moulpali: "Moulpali",
mountains-of-christmas: "Mountains of Christmas",
mouse-memoirs: "Mouse Memoirs",
mr-bedfort: "Mr Bedfort",
mr-dafoe: "Mr Dafoe",
mr-de-haviland: "Mr De Haviland",
mrs-saint-delafield: "Mrs Saint Delafield",
mrs-sheppards: "Mrs Sheppards",
mukta-vaani: "Mukta Vaani",
muli: "Muli",
mystery-quest: "Mystery Quest",
ntr: "NTR",
neucha: "Neucha",
neuton: "Neuton",
new-rocker: "New Rocker",
news-cycle: "News Cycle",
niconne: "Niconne",
nixie-one: "Nixie One",
nobile: "Nobile",
nokora: "Nokora",
norican: "Norican",
nosifer: "Nosifer",
nothing-you-could-do: "Nothing You Could Do",
noticia-text: "Noticia Text",
noto-sans: "Noto Sans",
noto-serif: "Noto Serif",
nova-cut: "Nova Cut",
nova-flat: "Nova Flat",
nova-mono: "Nova Mono",
nova-oval: "Nova Oval",
nova-round: "Nova Round",
nova-script: "Nova Script",
nova-slim: "Nova Slim",
nova-square: "Nova Square",
numans: "Numans",
nunito: "Nunito",
nunito-sans: "Nunito Sans",
odor-mean-chey: "Odor Mean Chey",
offside: "Offside",
old-standard-tt: "Old Standard TT",
oldenburg: "Oldenburg",
oleo-script: "Oleo Script",
oleo-script-swash-caps: "Oleo Script Swash Caps",
open-sans: "Open Sans",
open-sans-condensed: "Open Sans Condensed",
oranienbaum: "Oranienbaum",
orbitron: "Orbitron",
oregano: "Oregano",
orienta: "Orienta",
original-surfer: "Original Surfer",
oswald: "Oswald",
over-the-rainbow: "Over the Rainbow",
overlock: "Overlock",
overlock-sc: "Overlock SC",
overpass: "Overpass",
overpass-mono: "Overpass Mono",
ovo: "Ovo",
oxygen: "Oxygen",
oxygen-mono: "Oxygen Mono",
pt-mono: "PT Mono",
pt-sans: "PT Sans",
pt-sans-caption: "PT Sans Caption",
pt-sans-narrow: "PT Sans Narrow",
pt-serif: "PT Serif",
pt-serif-caption: "PT Serif Caption",
pacifico: "Pacifico",
padauk: "Padauk",
palanquin: "Palanquin",
palanquin-dark: "Palanquin Dark",
pangolin: "Pangolin",
paprika: "Paprika",
parisienne: "Parisienne",
passero-one: "Passero One",
passion-one: "Passion One",
pathway-gothic-one: "Pathway Gothic One",
patrick-hand: "Patrick Hand",
patrick-hand-sc: "Patrick Hand SC",
pattaya: "Pattaya",
patua-one: "Patua One",
pavanam: "Pavanam",
paytone-one: "Paytone One",
peddana: "Peddana",
peralta: "Peralta",
permanent-marker: "Permanent Marker",
petit-formal-script: "Petit Formal Script",
petrona: "Petrona",
philosopher: "Philosopher",
piedra: "Piedra",
pinyon-script: "Pinyon Script",
pirata-one: "Pirata One",
plaster: "Plaster",
play: "Play",
playball: "Playball",
playfair-display: "Playfair Display",
playfair-display-sc: "Playfair Display SC",
podkova: "Podkova",
poiret-one: "Poiret One",
poller-one: "Poller One",
poly: "Poly",
pompiere: "Pompiere",
pontano-sans: "Pontano Sans",
poppins: "Poppins",
port-lligat-sans: "Port Lligat Sans",
port-lligat-slab: "Port Lligat Slab",
pragati-narrow: "Pragati Narrow",
prata: "Prata",
preahvihear: "Preahvihear",
press-start-2p: "Press Start 2P",
pridi: "Pridi",
princess-sofia: "Princess Sofia",
prociono: "Prociono",
prompt: "Prompt",
prosto-one: "Prosto One",
proza-libre: "Proza Libre",
puritan: "Puritan",
purple-purse: "Purple Purse",
quando: "Quando",
quantico: "Quantico",
quattrocento: "Quattrocento",
quattrocento-sans: "Quattrocento Sans",
questrial: "Questrial",
quicksand: "Quicksand",
quintessential: "Quintessential",
qwigley: "Qwigley",
racing-sans-one: "Racing Sans One",
radley: "Radley",
rajdhani: "Rajdhani",
rakkas: "Rakkas",
raleway: "Raleway",
raleway-dots: "Raleway Dots",
ramabhadra: "Ramabhadra",
ramaraja: "Ramaraja",
rambla: "Rambla",
rammetto-one: "Rammetto One",
ranchers: "Ranchers",
rancho: "Rancho",
ranga: "Ranga",
rasa: "Rasa",
rationale: "Rationale",
ravi-prakash: "Ravi Prakash",
redressed: "Redressed",
reem-kufi: "Reem Kufi",
reenie-beanie: "Reenie Beanie",
revalia: "Revalia",
rhodium-libre: "Rhodium Libre",
ribeye: "Ribeye",
ribeye-marrow: "Ribeye Marrow",
righteous: "Righteous",
risque: "Risque",
roboto: "Roboto",
roboto-condensed: "Roboto Condensed",
roboto-mono: "Roboto Mono",
roboto-slab: "Roboto Slab",
rochester: "Rochester",
rock-salt: "Rock Salt",
rokkitt: "Rokkitt",
romanesco: "Romanesco",
ropa-sans: "Ropa Sans",
rosario: "Rosario",
rosarivo: "Rosarivo",
rouge-script: "Rouge Script",
rozha-one: "Rozha One",
rubik: "Rubik",
rubik-mono-one: "Rubik Mono One",
ruda: "Ruda",
rufina: "Rufina",
ruge-boogie: "Ruge Boogie",
ruluko: "Ruluko",
rum-raisin: "Rum Raisin",
ruslan-display: "Ruslan Display",
russo-one: "Russo One",
ruthie: "Ruthie",
rye: "Rye",
sacramento: "Sacramento",
sahitya: "Sahitya",
sail: "Sail",
salsa: "Salsa",
sanchez: "Sanchez",
sancreek: "Sancreek",
sansita: "Sansita",
sarala: "Sarala",
sarina: "Sarina",
sarpanch: "Sarpanch",
satisfy: "Satisfy",
scada: "Scada",
scheherazade: "Scheherazade",
schoolbell: "Schoolbell",
scope-one: "Scope One",
seaweed-script: "Seaweed Script",
secular-one: "Secular One",
sevillana: "Sevillana",
seymour-one: "Seymour One",
shadows-into-light: "Shadows Into Light",
shadows-into-light-two: "Shadows Into Light Two",
shanti: "Shanti",
share: "Share",
share-tech: "Share Tech",
share-tech-mono: "Share Tech Mono",
shojumaru: "Shojumaru",
short-stack: "Short Stack",
shrikhand: "Shrikhand",
siemreap: "Siemreap",
sigmar-one: "Sigmar One",
signika: "Signika",
signika-negative: "Signika Negative",
simonetta: "Simonetta",
sintony: "Sintony",
sirin-stencil: "Sirin Stencil",
six-caps: "Six Caps",
skranji: "Skranji",
slabo-13px: "Slabo 13px",
slabo-27px: "Slabo 27px",
slackey: "Slackey",
smokum: "Smokum",
smythe: "Smythe",
sniglet: "Sniglet",
snippet: "Snippet",
snowburst-one: "Snowburst One",
sofadi-one: "Sofadi One",
sofia: "Sofia",
sonsie-one: "Sonsie One",
sorts-mill-goudy: "Sorts Mill Goudy",
source-code-pro: "Source Code Pro",
source-sans-pro: "Source Sans Pro",
source-serif-pro: "Source Serif Pro",
space-mono: "Space Mono",
special-elite: "Special Elite",
spicy-rice: "Spicy Rice",
spinnaker: "Spinnaker",
spirax: "Spirax",
squada-one: "Squada One",
sree-krushnadevaraya: "Sree Krushnadevaraya",
sriracha: "Sriracha",
stalemate: "Stalemate",
stalinist-one: "Stalinist One",
stardos-stencil: "Stardos Stencil",
stint-ultra-condensed: "Stint Ultra Condensed",
stint-ultra-expanded: "Stint Ultra Expanded",
stoke: "Stoke",
strait: "Strait",
sue-ellen-francisco: "Sue Ellen Francisco",
suez-one: "Suez One",
sumana: "Sumana",
sunshiney: "Sunshiney",
supermercado-one: "Supermercado One",
sura: "Sura",
suranna: "Suranna",
suravaram: "Suravaram",
suwannaphum: "Suwannaphum",
swanky-and-moo-moo: "Swanky and Moo Moo",
syncopate: "Syncopate",
tangerine: "Tangerine",
taprom: "Taprom",
tauri: "Tauri",
taviraj: "Taviraj",
teko: "Teko",
telex: "Telex",
tenali-ramakrishna: "Tenali Ramakrishna",
tenor-sans: "Tenor Sans",
text-me-one: "Text Me One",
the-girl-next-door: "The Girl Next Door",
tienne: "Tienne",
tillana: "Tillana",
timmana: "Timmana",
tinos: "Tinos",
titan-one: "Titan One",
titillium-web: "Titillium Web",
trade-winds: "Trade Winds",
trirong: "Trirong",
trocchi: "Trocchi",
trochut: "Trochut",
trykker: "Trykker",
tulpen-one: "Tulpen One",
ubuntu: "Ubuntu",
ubuntu-condensed: "Ubuntu Condensed",
ubuntu-mono: "Ubuntu Mono",
ultra: "Ultra",
uncial-antiqua: "Uncial Antiqua",
underdog: "Underdog",
unica-one: "Unica One",
unifrakturcook: "UnifrakturCook",
unifrakturmaguntia: "UnifrakturMaguntia",
unkempt: "Unkempt",
unlock: "Unlock",
unna: "Unna",
vt323: "VT323",
vampiro-one: "Vampiro One",
varela: "Varela",
varela-round: "Varela Round",
vast-shadow: "Vast Shadow",
vesper-libre: "Vesper Libre",
vibur: "Vibur",
vidaloka: "Vidaloka",
viga: "Viga",
voces: "Voces",
volkhov: "Volkhov",
vollkorn: "Vollkorn",
voltaire: "Voltaire",
waiting-for-the-sunrise: "Waiting for the Sunrise",
wallpoet: "Wallpoet",
walter-turncoat: "Walter Turncoat",
warnes: "Warnes",
wellfleet: "Wellfleet",
wendy-one: "Wendy One",
wire-one: "Wire One",
work-sans: "Work Sans",
yanone-kaffeesatz: "Yanone Kaffeesatz",
yantramanav: "Yantramanav",
yatra-one: "Yatra One",
yellowtail: "Yellowtail",
yeseva-one: "Yeseva One",
yesteryear: "Yesteryear",
yrsa: "Yrsa",
zeyada: "Zeyada"`;


const result = process.split(',\n')
  .map(line => {
    const [key, value] = line.split(':');
    return `"${key}":${value}`;
  })
  .join(',\n');

const json = `{ \n ${result} \n }`;

module.exports = JSON.parse(json);
